version: "3"
services:
  nginx:
    build:
        dockerfile: ./docker/nginx.dockerfile
        context: .
    image: lildemarms/nginx
    container_name: nginx
    ports:
      - "80:80"
    networks: 
      - production-network
    depends_on: 
      - "app1"
      - "app2"
      - "app3"

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017
    networks: 
      - production-network

  app1:
    image: lildemarms/associate-assembly
    container_name: app-1
    ports:
      - 8080
    networks: 
      - production-network
    depends_on:
      - "mongodb"
    links:
      - mongodb

  app2:
    image: lildemarms/associate-assembly
    container_name: app-2
    ports:
      - 8080
    networks: 
      - production-network
    depends_on:
      - "mongodb"
    links:
      - mongodb
      
  app3:
    image: lildemarms/associate-assembly
    container_name: app-3
    ports:
      - 8080
    networks: 
      - production-network
    depends_on:
      - "mongodb"
    links:
      - mongodb
      
networks: 
    production-network:
        driver: bridge